name: Build and Publish docker image

on:
  workflow_dispatch:
  
  push:
    branches: 
      - main
env:
  IMAGE: internal
  
jobs:
  build-test_node_project:
    name: build and test node code
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Use nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: '18.x'
          check-latest: true
          
      - name: Install dependencies for tests
        run: npm i
        
      - name: Run all tests
        run:  npm test
        
